### ISSUE TITLE
undefined reference to `LAPACKE_dgees' during catkin build on Ubuntu 20.04 Noetic

### ISSUE THREAD

**Issue by Anchor1566** [ethz-asl/mav_control_rw#49]
**Description**:

**System Environment**:
- OS: Ubuntu 20.04 LTS
- ROS Distro: Noetic
- Compiler: GCC 10.4.0

**Problem Description**:
Encountered a linker error while compiling the `mav_nonlinear_mpc` package with `catkin build`. The error indicates an undefined reference to `LAPACKE_dgees`, despite having `liblapacke-dev` installed.

**Steps to Reproduce**:
1. Install dependencies: `sudo apt-get install liblapacke-dev`
2. Execute build: `catkin build `
**Error Log**:
```
Errors     << mav_nonlinear_mpc:make /home/xun/Desktop/code/SDU/SLAM/github/voxblox_planner/logs/mav_nonlinear_mpc/build.make.062.log
/usr/bin/ld: /home/xun/Desktop/code/SDU/SLAM/github/voxblox_planner/devel/.private/mav_nonlinear_mpc/lib/libmav_nonlinear_mpc_lib.so: undefined reference to `LAPACKE_dgees'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/nonlinear_mpc_node.dir/build.make:114: /home/xun/Desktop/code/SDU/SLAM/github/voxblox_planner/devel/.private/mav_nonlinear_mpc/lib/mav_nonlinear_mpc/nonlinear_mpc_node] Error 1
make[1]: *** [CMakeFiles/Makefile2:311: CMakeFiles/nonlinear_mpc_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/xun/Desktop/code/SDU/SLAM/github/voxblox_planner/build/mav_nonlinear_mpc; catkin build --get-env mav_nonlinear_mpc | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -
```

**Comment by Anchor1566** [comment]
It has been resolved. The root cause was improper linking of the LAPACKE library within the CMakeLists.txt configuration.
```
cmake_minimum_required(VERSION 2.8.3)
project(mav_nonlinear_mpc)

set(CMAKE_BUILD_TYPE Release)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${PROJECT_SOURCE_DIR}/cmake/")

find_package(LAPACK REQUIRED)

# find LAPACKE
find_library(LAPACKE_LIB 
  NAMES lapacke liblapacke
  HINTS ${LAPACK_LIBRARIES} ${Openblas_LIBRARIES}
  PATH_SUFFIXES lib64 lib
)

find_package(OpenBLAS)
if (OpenBLAS_FOUND)
  message("-- Found OpenBLAS library: ${OpenBLAS_LIBRARIES}")
  message("-- Found OpenBLAS include dirs: ${OpenBLAS_INCLUDE_DIRS}")
  include_directories(${OpenBLAS_INCLUDE_DIRS})
  
  if(LAPACKE_LIB)
    set(LAPACKE_LIBRARIES ${LAPACKE_LIB})
  else()
    set(LAPACKE_LIBRARIES ${OpenBLAS_LIBRARIES})
  endif()
else()
  message("-- OpenBLAS not found, using system LAPACK/LAPACKE")
  
  if(NOT LAPACKE_LIB)
    message(FATAL_ERROR "LAPACKE library not found!")
  endif()
  
  set(LAPACKE_LIBRARIES ${LAPACKE_LIB})
endif()

set(LAPACKE_LIBRARIES ${LAPACKE_LIBRARIES} ${LAPACK_LIBRARIES})

find_package(catkin_simple REQUIRED)
catkin_simple(ALL_DEPS_REQUIRED)

if(APPLE)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -stdlib=libc++")
else()
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
endif()

find_package(Eigen REQUIRED)
include_directories(${Eigen_INCLUDE_DIRS})

#############
# LIBRARIES #
#############
cs_add_library(mav_nonlinear_mpc_lib
  src/nonlinear_mpc.cc
  solver/qpoases/SRC/Bounds.cpp
  solver/qpoases/SRC/Constraints.cpp
  solver/qpoases/SRC/CyclingManager.cpp
  solver/qpoases/SRC/Indexlist.cpp
  solver/qpoases/SRC/MessageHandling.cpp
  solver/qpoases/SRC/QProblem.cpp
  solver/qpoases/SRC/QProblemB.cpp
  solver/qpoases/SRC/SubjectTo.cpp
  solver/qpoases/SRC/Utils.cpp
  solver/qpoases/SRC/EXTRAS/SolutionAnalysis.cpp
  solver/acado_qpoases_interface.cpp
  solver/acado_integrator.c
  solver/acado_solver.c
  solver/acado_auxiliary_functions.c
  )

target_include_directories(mav_nonlinear_mpc_lib PUBLIC
	solver/
	solver/qpoases
	solver/qpoases/INCLUDE
	solver/qpoases/SRC
	)

############
# BINARIES #
############
cs_add_executable(nonlinear_mpc_node
  src/nonlinear_mpc_node.cc
)

target_link_libraries(mav_nonlinear_mpc_lib PUBLIC ${LAPACKE_LIBRARIES})

target_link_libraries(nonlinear_mpc_node mav_nonlinear_mpc_lib ${LAPACKE_LIBRARIES})

add_dependencies(nonlinear_mpc_node ${${PROJECT_NAME}_EXPORTED_TARGETS})

##########
# EXPORT #
##########
cs_install()
cs_export()
```
